import type { LucideIcon } from 'lucide-react';
import {
  Aperture,
  BookOpen,
  Bot,
  Boxes,
  Brush,
  Calendar,
  Camera,
  Cloud,
  Code,
  CodeXml,
  Coffee,
  Command,
  Compass,
  Container,
  Cpu,
  Database,
  FileCode,
  Flame,
  Gamepad2,
  GitBranch,
  Globe,
  Heart,
  Hexagon,
  Image,
  KanbanSquare,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Mail,
  Monitor,
  Music,
  Palette,
  PenTool,
  Puzzle,
  Rocket,
  Search,
  Server,
  Settings,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Terminal,
  Wrench,
  Zap,
} from 'lucide-react';

const REGISTRY: Record<string, LucideIcon> = {
  terminal: Terminal,
  'book-open': BookOpen,
  sparkles: Sparkles,
  'layout-dashboard': LayoutDashboard,
  dashboard: LayoutDashboard,
  'kanban-square': KanbanSquare,
  kanban: KanbanSquare,
  brush: Brush,
  database: Database,
  shield: Shield,
  code: Code,
  'code-xml': CodeXml,
  rocket: Rocket,
  zap: Zap,
  globe: Globe,
  layers: Layers,
  cpu: Cpu,
  palette: Palette,
  camera: Camera,
  music: Music,
  bot: Bot,
  'gamepad-2': Gamepad2,
  gamepad: Gamepad2,
  'git-branch': GitBranch,
  git: GitBranch,
  container: Container,
  cloud: Cloud,
  server: Server,
  smartphone: Smartphone,
  monitor: Monitor,
  wrench: Wrench,
  settings: Settings,
  heart: Heart,
  star: Star,
  flame: Flame,
  coffee: Coffee,
  lightbulb: Lightbulb,
  search: Search,
  mail: Mail,
  calendar: Calendar,
  'file-code': FileCode,
  filecode: FileCode,
  boxes: Boxes,
  puzzle: Puzzle,
  hexagon: Hexagon,
  command: Command,
  compass: Compass,
  aperture: Aperture,
  'pen-tool': PenTool,
  pentool: PenTool,
  image: Image,
};

export const CURATED_ICONS = [
  'terminal',
  'code',
  'file-code',
  'database',
  'server',
  'cloud',
  'globe',
  'rocket',
  'zap',
  'layers',
  'layout-dashboard',
  'kanban-square',
  'brush',
  'palette',
  'pen-tool',
  'camera',
  'image',
  'music',
  'gamepad-2',
  'bot',
  'cpu',
  'monitor',
  'smartphone',
  'shield',
  'container',
  'boxes',
  'git-branch',
  'wrench',
  'settings',
  'heart',
  'star',
  'flame',
  'coffee',
  'lightbulb',
  'search',
  'mail',
] as const;

function normalize(value: string): string {
  return value.replace(/[^a-z0-9]/gi, '').toLowerCase();
}

export function resolveAppIcon(icon?: string): LucideIcon | null {
  if (!icon) return null;
  return REGISTRY[normalize(icon)] ?? null;
}

export function isImageSource(value?: string): boolean {
  if (!value) return false;
  return (
    /^(https?:)?\/\//i.test(value) ||
    value.startsWith('/') ||
    value.startsWith('data:image')
  );
}
