import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  // Runs synchronously before the body paints: pulls the saved document
  // straight from localStorage and applies skin/accent/font to <html>, so
  // even the first frame already wears the visitor's theme (no HUD flash).
  // A persisted visitor skin override (SkinSwitcher pick, incl. 'auto')
  // wins over the document's official default — and survives navigation
  // to the standalone /write and /blog routes.
  const prePaintTheme = `
    try {
      var d = JSON.parse(localStorage.getItem('portfolio-data') || 'null');
      var el = document.documentElement;
      var t = (d && typeof d === 'object' && d.theme) || {};
      var locked = t.lockSkin === true;
      var over = locked ? null : localStorage.getItem('portfolio-skin-override');
      var skins = ['hud', 'notebook', 'clean'];
      if (over === 'auto') {
        over = window.matchMedia('(prefers-color-scheme: dark)').matches
          ? 'hud'
          : 'clean';
      }
      if (!locked && skins.includes(over)) {
        el.dataset.skin = over;
      } else if (d && typeof d === 'object' && d.skin) {
        el.dataset.skin = d.skin;
      }
      if (t.accentColor) el.style.setProperty('--accent', t.accentColor);
      if (t.fontFamily) {
        el.style.setProperty('--font', t.fontFamily);
        el.style.setProperty('--font-custom', t.fontFamily);
      }
    } catch (e) {}
  `;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <script dangerouslySetInnerHTML={{ __html: prePaintTheme }} />
        {children}
      </body>
    </html>
  );
}
